# Generated by Django 2.1 on 2018-08-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type_description', models.CharField(max_length=120)),
                ('document_id', models.CharField(max_length=80)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('default_vat_rate', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=80)),
                ('payment_expectation', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gross_amount_foreign', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Employee')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.PaymentType')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Procedure')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Country'),
        ),
        migrations.AddField(
            model_name='cost',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Procedure'),
        ),
        migrations.AddField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashapp.Project'),
        ),
    ]
