# Generated by Django 2.1 on 2018-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='building_no',
            field=models.CharField(max_length=120, null=True, verbose_name='no.'),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='company',
            name='flat_no',
            field=models.CharField(max_length=120, null=True, verbose_name='Flat no.'),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=120, null=True, verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(max_length=120, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_no',
            field=models.CharField(max_length=20, verbose_name='Tax no.'),
        ),
    ]
