# Generated by Django 2.1 on 2018-08-16 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='document_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='expected_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='payment_deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='settlement_status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='document_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='expected_payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='payment_deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='settlement_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cost',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashapp.Country'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=4),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashapp.Country'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashapp.Currency'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashapp.Employee'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='payment_expectation',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=4),
        ),
    ]
