# Generated by Django 2.1 on 2018-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_auto_20180826_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='building_no',
            field=models.CharField(max_length=120, null=True, verbose_name='Building no.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tax no.'),
        ),
    ]
