# Generated by Django 2.1 on 2018-08-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0002_auto_20180816_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='gross_amount',
            new_name='net_amount',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='gross_amount_foreign',
            new_name='net_amount_foreign',
        ),
    ]
