# Generated by Django 2.1 on 2018-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0004_companymember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='paymenttype',
            old_name='company',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='procedure',
            old_name='company',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='owner',
        ),
    ]
