# Generated by Django 2.1 on 2018-08-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0007_auto_20180828_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostCategory',
            new_name='ExpenseCategory',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='expected_payment_date',
            new_name='actual_payment_date',
        ),
        migrations.RenameField(
            model_name='revenue',
            old_name='expected_payment_date',
            new_name='actual_payment_date',
        ),
    ]
