# Generated by Django 2.1 on 2018-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0008_auto_20180829_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='actual_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='actual_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='payment_expectation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, null=True),
        ),
    ]
