# Generated by Django 2.1 on 2018-08-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashapp', '0009_auto_20180829_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashapp.Company'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashapp.Company'),
        ),
    ]
